import type { Lang } from '../../shared/i18n';

export type LikelyTier = 'normal' | 'spicy' | 'wild';
export const LIKELY_TIERS: LikelyTier[] = ['normal', 'spicy', 'wild'];

/**
 * 「谁最有可能……」题库，中文分三档尺度（每档 50 题）。
 * 渲染时前面拼上「谁最有可能」。变态版守红线：仅成人自愿，无违法 / 未成年 / 非自愿 / 伤害内容。
 */
const zh: Record<LikelyTier, string[]> = {
  normal: [
    '今晚第一个喝倒',
    '酒后给前任发消息',
    '偷偷在谈恋爱不告诉大家',
    '明天宿醉迟到',
    '三十岁前当上老板',
    'KTV 抢麦不放手',
    '把这顿饭拍照发朋友圈',
    '喝多了开始哭',
    '喝多了笑场停不下来',
    '聚会第一个偷偷溜走',
    '酒桌上吹牛最多',
    '说要减肥又点了炸鸡',
    '手机里自拍存最多',
    '谈恋爱秒回消息',
    '上班摸鱼最多',
    '最舍得给自己花钱',
    '旅行说走就走',
    '最会哄人开心',
    '最容易被忽悠',
    '喝醉了开始讲大道理',
    '守不住秘密',
    '半夜还在刷手机不睡',
    '中彩票也马上花光',
    '最怕另一半',
    '群里抢红包最快',
    '一言不合就唱歌',
    '点外卖从不看价格',
    '把闹钟按掉继续睡',
    '答应了健身从没去过',
    '永远在找眼镜手机钥匙',
    '聚餐时第一个动筷',
    '追剧能一天刷完一季',
    '永远是迟到的那个',
    '钱包里现金最少',
    '出门必回家拿落下的东西',
    '把全公司八卦都知道',
    '最容易冲动下单',
    '表情包存最多',
    '喝奶茶比喝水多',
    '养一堆多肉养死',
    '朋友圈点赞之交最多',
    '永远记不住别人名字',
    '被路边小猫小狗拐走',
    '聚会结束最舍不得走',
    '最容易笑场把秘密说漏',
    '朋友圈设三天可见',
    '收藏了一堆教程从不看',
    '最爱给朋友当军师',
    '答应早睡结果熬最晚',
    '最会自己跟自己聊天',
  ],
  spicy: [
    '在座的谁最是恋爱脑',
    '酒后最容易跟陌生人走',
    '同时撩过好几个人',
    '暗恋过在座的某位',
    '跟前任藕断丝连',
    '朋友圈秀恩爱最多',
    '表白被拒过最多次',
    '最敢在大庭广众下亲对象',
    '谈过姐弟恋或忘年恋',
    '备胎养得最多',
    '最容易喝醉后表白',
    '跟网友奔现过',
    '同时被好几个人追',
    '最会发暧昧短信',
    '翻暗恋对象朋友圈翻到几年前',
    '谈恋爱最快说我爱你',
    '最容易被颜值收买',
    '约会迟到还理直气壮',
    '跟朋友的前任暧昧过',
    '把某个人删了又加回来',
    '最会装清纯',
    '喝多了最容易动手动脚',
    '谈过最多段恋爱',
    '最会用身材优势',
    '半夜 emo 给暧昧对象打电话',
    '最敢穿得辣去蹦迪',
    '跟同事或同学有过地下情',
    '接受过最贵的礼物',
    '最会甜言蜜语骗人',
    '最敢在群里发自己的美照',
    '谈恋爱最舍得为对象花钱',
    '有过一段不能说的关系',
    '最容易被撩动心',
    '暧昧对象超过三个',
    '最会欲擒故纵',
    '喝醉后最容易跟人接吻',
    '最敢主动出击表白',
    '蹦迪最容易被搭讪',
    '跟前任复合过最多次',
    '收过最多情书或告白',
    '最会调情',
    '最容易因为寂寞谈恋爱',
    '在感情里最舍得豁出去',
    '朋友圈深夜发文最暧昧',
    '同一时间脚踏两条船',
    '最敢跟暧昧对象单独过夜',
    '把约会照偷偷设成屏保',
    '最容易日久生情',
    '相亲次数最多',
    '最会装作不在意其实很在意',
  ],
  wild: [
    '看过的小电影最多',
    '最敢在车里亲热',
    '床上花样最多',
    '一夜情次数最多',
    '收藏夹里有不可描述的内容',
    '最敢玩角色扮演',
    '在公共场合做过羞羞的事',
    '最早开始性启蒙',
    '同时跟多人有过关系',
    '最敢看着对方眼睛开黄腔',
    '抽屉里藏着成人玩具',
    '最容易被撩到上头',
    '接受过最大胆的要求',
    '最敢主动提尺度要求',
    '在奇怪的地方亲热过',
    '暧昧短信发得最露骨',
    '最敢发自己的私密照',
    '看片口味最重',
    '最敢当面讲荤段子',
    '跟刚认识的人就擦枪走火',
    '玩过最刺激的花样',
    '浴室里发生过故事',
    '最敢公开谈论性话题',
    '床伴换得最勤',
    '最会撩到人腿软',
    '偷偷买过情趣用品',
    '酒后最容易把持不住',
    '最敢答应一夜情',
    '谈过尺度最开放的对象',
    '在朋友家过夜发生过事',
    '最敢玩真心话里的露骨题',
    '最享受征服或被征服',
    '收过最露骨的情话',
    '出差旅行最容易有艳遇',
    '最敢半夜约人见面',
    '跟暧昧对象进展到身体最快',
    '最敢在镜子前拍辣照',
    '经历过最大胆的表白方式',
    '浴巾掉了也面不改色',
    '最容易酒后跟人过夜',
    '把暧昧聊到最露骨那个',
    '床上最主动',
    '最敢尝试新花样',
    '私密经历最丰富',
    '最早交出第一次',
    '一晚上记录最高',
    '最敢素颜裸睡见人',
    '同时维持多段暧昧关系',
    '最会用眼神勾人',
    '最敢把party玩到天亮还不散',
  ],
};

// 英文暂时只提供一桌人都能玩的安全题库，不分档（中文专属三档尺度）。
const en: string[] = [
  'pass out first tonight',
  'text an ex after drinking',
  'be secretly dating someone',
  'show up hungover tomorrow',
  'become a boss before 30',
  'hog the mic at karaoke',
  'post this dinner online',
  'cry when drunk',
  'laugh uncontrollably when drunk',
  'have a crush on someone here',
  'sneak out of the party first',
  'brag the most at the table',
  'order fried chicken after saying "diet"',
  'have the most selfies on their phone',
  'reply to a crush instantly',
  'slack off most at work',
  'splurge on themselves',
  'book a trip on a whim',
  'cheer everyone up best',
  'fall for an obvious scam',
  'give life lectures when drunk',
  'fail to keep a secret',
  'still be on their phone at 3am',
  'win the lottery and spend it all',
  'be scared of their partner',
  'grab the red packet fastest',
  'break into song randomly',
  'never check the price on takeout',
];

export function likelyDeck(lang: Lang, tier: LikelyTier): string[] {
  return lang === 'en' ? en : zh[tier];
}

/** 中文才分档；英文只有一套通用题库 */
export function hasTiers(lang: Lang): boolean {
  return lang === 'zh';
}
