import type { Lang } from '../../shared/i18n';

/** 「谁最有可能……」题库（日常版尺度）。渲染时前面会拼上「谁最有可能」标题。 */
export const LIKELY_DECK: Record<Lang, string[]> = {
  zh: [
    '今晚第一个喝倒',
    '酒后给前任发消息',
    '偷偷在谈恋爱不告诉大家',
    '明天宿醉迟到',
    '三十岁前当上老板',
    'KTV 抢麦不放手',
    '把这顿饭拍照发朋友圈',
    '喝多了开始哭',
    '喝多了笑场停不下来',
    '偷偷喜欢着在座的某个人',
    '聚会第一个偷偷溜走',
    '酒桌上吹牛最多',
    '说要减肥又点了炸鸡',
    '手机里自拍存最多',
    '谈恋爱秒回消息',
    '上班摸鱼最多',
    '最舍得给自己花钱',
    '旅行说走就走',
    '最会哄人开心',
    '最容易被忽悠',
    '喝醉了开始讲大道理',
    '守不住秘密',
    '半夜还在刷手机不睡',
    '中彩票也马上花光',
    '最怕另一半',
    '群里抢红包最快',
    '一言不合就唱歌',
    '点外卖从不看价格',
  ],
  en: [
    'pass out first tonight',
    'text an ex after drinking',
    'be secretly dating someone',
    'show up hungover tomorrow',
    'become a boss before 30',
    'hog the mic at karaoke',
    'post this dinner online',
    'cry when drunk',
    'laugh uncontrollably when drunk',
    'have a crush on someone here',
    'sneak out of the party first',
    'brag the most at the table',
    'order fried chicken after saying "diet"',
    'have the most selfies on their phone',
    'reply to a crush instantly',
    'slack off most at work',
    'splurge on themselves',
    'book a trip on a whim',
    'cheer everyone up best',
    'fall for an obvious scam',
    'give life lectures when drunk',
    'fail to keep a secret',
    'still be on their phone at 3am',
    'win the lottery and spend it all',
    'be scared of their partner',
    'grab the red packet fastest',
    'break into song randomly',
    'never check the price on takeout',
  ],
};
