import type { Transfer, Trip } from './types';
import { formatMoney } from './money';
import { tripTotalCents } from './balance';

/** 生成可直接复制发群的结算文案。 */
export function settlementText(trip: Trip, transfers: Transfer[], lang: 'zh' | 'en'): string {
  const nameOf = (id: string) => trip.members.find((m) => m.id === id)?.name ?? '?';
  const count = trip.expenses.filter((e) => e.kind !== 'repayment').length;
  const total = formatMoney(tripTotalCents(trip), trip.currency);

  const lines =
    lang === 'zh'
      ? [`【${trip.name} · 分账结果】共 ${count} 笔 ${total}`, '────────────']
      : [`[${trip.name} · Settlement] ${count} expenses, ${total}`, '────────────'];

  if (transfers.length === 0) {
    lines.push(lang === 'zh' ? '账目已平，无需转账 ✅' : 'All settled, no transfers needed ✅');
  } else {
    for (const t of transfers) {
      lines.push(`${nameOf(t.from)} → ${nameOf(t.to)} ${formatMoney(t.amountCents, trip.currency)}`);
    }
    lines.push(lang === 'zh' ? `共 ${transfers.length} 笔转清 ✅` : `Settled in ${transfers.length} transfers ✅`);
  }
  lines.push(lang === 'zh' ? '由 Farely 生成' : 'Generated by Farely');
  return lines.join('\n');
}
